//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gchat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gchat.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend &amp; Server Development.
        /// </summary>
        public static string About_BackendDeveloperHeader {
            get {
                return ResourceManager.GetString("About_BackendDeveloperHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3 Codename Lassi
        ///· Search
        ///· Recent contacts
        ///· Status change
        ///· Bugfixes
        ///
        ///1.2 Codename Mousse
        ///· Fixed a bug with the display pictures
        ///· Extended timeout period to 30 seconds
        ///· Fixed a couple of crashes
        ///
        ///1.1 Codename Jelly
        ///· Initial release!.
        /// </summary>
        public static string About_ChangelistBody {
            get {
                return ResourceManager.GetString("About_ChangelistBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelist.
        /// </summary>
        public static string About_ChangelistHeader {
            get {
                return ResourceManager.GetString("About_ChangelistHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a third party app and is not endorsed or supported by Google..
        /// </summary>
        public static string About_Disclaimer {
            get {
                return ResourceManager.GetString("About_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like this application?.
        /// </summary>
        public static string About_Feedback1 {
            get {
                return ResourceManager.GetString("About_Feedback1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know!.
        /// </summary>
        public static string About_Feedback2 {
            get {
                return ResourceManager.GetString("About_Feedback2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you find a bug?.
        /// </summary>
        public static string About_Feedback3 {
            get {
                return ResourceManager.GetString("About_Feedback3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report it!.
        /// </summary>
        public static string About_Feedback4 {
            get {
                return ResourceManager.GetString("About_Feedback4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the free version. It&apos;s not limited or anything because we love you. Please consider getting the.
        /// </summary>
        public static string About_FreeVersionNotice1 {
            get {
                return ResourceManager.GetString("About_FreeVersionNotice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paid version.
        /// </summary>
        public static string About_FreeVersionNotice2 {
            get {
                return ResourceManager.GetString("About_FreeVersionNotice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to support the development of this app (and paying the servers)..
        /// </summary>
        public static string About_FreeVersionNotice3 {
            get {
                return ResourceManager.GetString("About_FreeVersionNotice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend Development &amp; UI Design.
        /// </summary>
        public static string About_FrontendDeveloperHeader {
            get {
                return ResourceManager.GetString("About_FrontendDeveloperHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About_Header {
            get {
                return ResourceManager.GetString("About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source!.
        /// </summary>
        public static string About_License1 {
            get {
                return ResourceManager.GetString("About_License1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the code at GitHub.
        /// </summary>
        public static string About_License2 {
            get {
                return ResourceManager.GetString("About_License2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under a.
        /// </summary>
        public static string About_License3 {
            get {
                return ResourceManager.GetString("About_License3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC BY-NC-SA license.
        /// </summary>
        public static string About_License4 {
            get {
                return ResourceManager.GetString("About_License4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the paid version of Gchat. It has no extra funcionality, but you can have the warm, fuzzy feeling that you contributed to this app&apos;s development..
        /// </summary>
        public static string About_PaidVersionNotice {
            get {
                return ResourceManager.GetString("About_PaidVersionNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gchat 1.3.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gchat.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attach.
        /// </summary>
        public static string Chat_AppbarAttach {
            get {
                return ResourceManager.GetString("Chat_AppbarAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete thread.
        /// </summary>
        public static string Chat_AppbarDeleteThread {
            get {
                return ResourceManager.GetString("Chat_AppbarDeleteThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end otr.
        /// </summary>
        public static string Chat_AppbarEndOtr {
            get {
                return ResourceManager.GetString("Chat_AppbarEndOtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go otr.
        /// </summary>
        public static string Chat_AppbarGoOtr {
            get {
                return ResourceManager.GetString("Chat_AppbarGoOtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string Chat_AppbarPin {
            get {
                return ResourceManager.GetString("Chat_AppbarPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string Chat_AppbarSend {
            get {
                return ResourceManager.GetString("Chat_AppbarSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view contact list.
        /// </summary>
        public static string Chat_AppbarViewContacts {
            get {
                return ResourceManager.GetString("Chat_AppbarViewContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Try logging in again..
        /// </summary>
        public static string Chat_ErrorAuthExpiredBody {
            get {
                return ResourceManager.GetString("Chat_ErrorAuthExpiredBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error.
        /// </summary>
        public static string Chat_ErrorAuthExpiredTitle {
            get {
                return ResourceManager.GetString("Chat_ErrorAuthExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not sent. Please try again later.
        /// </summary>
        public static string Chat_ErrorMessageNotSent {
            get {
                return ResourceManager.GetString("Chat_ErrorMessageNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading photo.
        /// </summary>
        public static string Chat_ErrorUploadingPhoto {
            get {
                return ResourceManager.GetString("Chat_ErrorUploadingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded your hourly quota of 50 image uploads per hour. Please wait some time and try again..
        /// </summary>
        public static string Chat_ErrorUploadingPhotoApiLimitExceeded {
            get {
                return ResourceManager.GetString("Chat_ErrorUploadingPhotoApiLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading the image timed out. Please try again..
        /// </summary>
        public static string Chat_ErrorUploadingPhotoTimeout {
            get {
                return ResourceManager.GetString("Chat_ErrorUploadingPhotoTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conversation is no longer off the record..
        /// </summary>
        public static string Chat_NoticeEndOtr {
            get {
                return ResourceManager.GetString("Chat_NoticeEndOtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conversation is now off the record..
        /// </summary>
        public static string Chat_NoticeStartOtr {
            get {
                return ResourceManager.GetString("Chat_NoticeStartOtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is typing....
        /// </summary>
        public static string Chat_NoticeTyping {
            get {
                return ResourceManager.GetString("Chat_NoticeTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message....
        /// </summary>
        public static string Chat_ProgressSendingMessage {
            get {
                return ResourceManager.GetString("Chat_ProgressSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading photo....
        /// </summary>
        public static string Chat_ProgressUploadingPhoto {
            get {
                return ResourceManager.GetString("Chat_ProgressUploadingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All messages in this thread will be deleted from the app. They may still persist in your Gmail chat history..
        /// </summary>
        public static string Chat_WarningDeleteThreadBody {
            get {
                return ResourceManager.GetString("Chat_WarningDeleteThreadBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete thread?.
        /// </summary>
        public static string Chat_WarningDeleteThreadTitle {
            get {
                return ResourceManager.GetString("Chat_WarningDeleteThreadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached images are hosted publicly on Imgur. Don&apos;t use this feature if you want to keep the images private.
        ///This warning will now show again after you press OK..
        /// </summary>
        public static string Chat_WarningImagesBody {
            get {
                return ResourceManager.GetString("Chat_WarningImagesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use image attachments feature?.
        /// </summary>
        public static string Chat_WarningImagesTitle {
            get {
                return ResourceManager.GetString("Chat_WarningImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available.
        /// </summary>
        public static string ChatStatus_Available {
            get {
                return ResourceManager.GetString("ChatStatus_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVAILABLE.
        /// </summary>
        public static string ChatStatus_AvailableUpper {
            get {
                return ResourceManager.GetString("ChatStatus_AvailableUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to away.
        /// </summary>
        public static string ChatStatus_Away {
            get {
                return ResourceManager.GetString("ChatStatus_Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWAY.
        /// </summary>
        public static string ChatStatus_AwayUpper {
            get {
                return ResourceManager.GetString("ChatStatus_AwayUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to busy.
        /// </summary>
        public static string ChatStatus_Busy {
            get {
                return ResourceManager.GetString("ChatStatus_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUSY.
        /// </summary>
        public static string ChatStatus_BusyUpper {
            get {
                return ResourceManager.GetString("ChatStatus_BusyUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invisible.
        /// </summary>
        public static string ChatStatus_Invisible {
            get {
                return ResourceManager.GetString("ChatStatus_Invisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVISIBLE.
        /// </summary>
        public static string ChatStatus_InvisibleUpper {
            get {
                return ResourceManager.GetString("ChatStatus_InvisibleUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offline.
        /// </summary>
        public static string ChatStatus_Offline {
            get {
                return ResourceManager.GetString("ChatStatus_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFLINE.
        /// </summary>
        public static string ChatStatus_OfflineUpper {
            get {
                return ResourceManager.GetString("ChatStatus_OfflineUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide contact.
        /// </summary>
        public static string Contact_ContextMenuHide {
            get {
                return ResourceManager.GetString("Contact_ContextMenuHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string Contact_ContextMenuPin {
            get {
                return ResourceManager.GetString("Contact_ContextMenuPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show contact.
        /// </summary>
        public static string Contact_ContextMenuUnhide {
            get {
                return ResourceManager.GetString("Contact_ContextMenuUnhide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string ContactList_AllHeader {
            get {
                return ResourceManager.GetString("ContactList_AllHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        public static string ContactList_AppbarLogOut {
            get {
                return ResourceManager.GetString("ContactList_AppbarLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string ContactList_AppbarRefresh {
            get {
                return ResourceManager.GetString("ContactList_AppbarRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string ContactList_AppbarSearch {
            get {
                return ResourceManager.GetString("ContactList_AppbarSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string ContactList_AppbarSettings {
            get {
                return ResourceManager.GetString("ContactList_AppbarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string ContactList_AppbarStatus {
            get {
                return ResourceManager.GetString("ContactList_AppbarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online.
        /// </summary>
        public static string ContactList_OnlineHeader {
            get {
                return ResourceManager.GetString("ContactList_OnlineHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading contacts....
        /// </summary>
        public static string ContactList_ProgressLoading {
            get {
                return ResourceManager.GetString("ContactList_ProgressLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent.
        /// </summary>
        public static string ContactList_RecentHeader {
            get {
                return ResourceManager.GetString("ContactList_RecentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET CHAT STATUS.
        /// </summary>
        public static string ContactList_StatusPickerHeader {
            get {
                return ResourceManager.GetString("ContactList_StatusPickerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACTS.
        /// </summary>
        public static string ContactList_Title {
            get {
                return ResourceManager.GetString("ContactList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key matching failed. Please get a new API Key and retry..
        /// </summary>
        public static string Error_ApiMessage {
            get {
                return ResourceManager.GetString("Error_ApiMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key failure.
        /// </summary>
        public static string Error_ApiTitle {
            get {
                return ResourceManager.GetString("Error_ApiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authentication token has expired. Try logging in again..
        /// </summary>
        public static string Error_AuthErrorMessage {
            get {
                return ResourceManager.GetString("Error_AuthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error.
        /// </summary>
        public static string Error_AuthErrorTitle {
            get {
                return ResourceManager.GetString("Error_AuthErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact server. Please retry later..
        /// </summary>
        public static string Error_ConnectionErrorMessage {
            get {
                return ResourceManager.GetString("Error_ConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string Error_ConnectionErrorTitle {
            get {
                return ResourceManager.GetString("Error_ConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get your contact list. Please retry later.&quot;.
        /// </summary>
        public static string Error_ContactListMessage {
            get {
                return ResourceManager.GetString("Error_ContactListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact list.
        /// </summary>
        public static string Error_ContactListTitle {
            get {
                return ResourceManager.GetString("Error_ContactListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get offline messages. Please retry later..
        /// </summary>
        public static string Error_OfflineMessagesMessage {
            get {
                return ResourceManager.GetString("Error_OfflineMessagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting offline messages.
        /// </summary>
        public static string Error_OfflineMessagesTitle {
            get {
                return ResourceManager.GetString("Error_OfflineMessagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Error_RegisterTitle {
            get {
                return ResourceManager.GetString("Error_RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string Login_AppbarLogin {
            get {
                return ResourceManager.GetString("Login_AppbarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Google account.
        /// </summary>
        public static string Login_CreateAccountLink {
            get {
                return ResourceManager.GetString("Login_CreateAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string Login_Header {
            get {
                return ResourceManager.GetString("Login_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google password.
        /// </summary>
        public static string Login_PasswordLabel {
            get {
                return ResourceManager.GetString("Login_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCHAT.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google username or email.
        /// </summary>
        public static string Login_UsernameLabel {
            get {
                return ResourceManager.GetString("Login_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By logging in, you are also opting in to raw, toast and tile push notifications for incoming chat messages. You can disable toast and tile notifications individually in the settings page at any time. Raw notifications are required for the app to function properly and can be disabled at any time by logging out..
        /// </summary>
        public static string Login_WarningNotifications {
            get {
                return ResourceManager.GetString("Login_WarningNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By logging out, all your settings will be erased. Do you wish to continue?.
        /// </summary>
        public static string Logout_Message {
            get {
                return ResourceManager.GetString("Logout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        public static string Logout_Title {
            get {
                return ResourceManager.GetString("Logout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unread messages.
        /// </summary>
        public static string Notification_OfflineMessages {
            get {
                return ResourceManager.GetString("Notification_OfflineMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCHAT.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddit-style icons.
        /// </summary>
        public static string Settings_ToggleReddit {
            get {
                return ResourceManager.GetString("Settings_ToggleReddit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen rotation.
        /// </summary>
        public static string Settings_ToggleRotation {
            get {
                return ResourceManager.GetString("Settings_ToggleRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable secondary tile notifications.
        /// </summary>
        public static string Settings_ToggleSecondaryTiles {
            get {
                return ResourceManager.GetString("Settings_ToggleSecondaryTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tile notifications.
        /// </summary>
        public static string Settings_ToggleTiles {
            get {
                return ResourceManager.GetString("Settings_ToggleTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable toast notifications.
        /// </summary>
        public static string Settings_ToggleToasts {
            get {
                return ResourceManager.GetString("Settings_ToggleToasts", resourceCulture);
            }
        }
    }
}
